In [1]:
import pandas as pd
import numpy as np

import encode

In [2]:
st_habits1 = pd.read_csv('student_habits.csv')         # raw data

st_habits1

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [4]:
st_habits1 = encode.data_rename(st_habits1)

In [5]:
st_habits1 = encode.data_encoding(st_habits1)          # encoded — same name, clean

In [9]:
st_habits1

,age,study_hrs,part_time_job,media_hrs,att_percent,sleep_hours,diet_quality,exercise_fq,internet_quality,mental_health_rating,extracurricular,exam_score,gender_Female,gender_Male,gender_Other,par_edu_Bachelor,par_edu_High School,par_edu_Master,par_edu_Unknown
0,23,0.0,0,2.3,85.0,8.0,1,6,1,8,1,56.2,1,0,0,0,0,1,0
1,20,6.9,0,5.1,97.3,4.6,2,6,1,8,0,100.0,1,0,0,0,1,0,0
2,21,1.4,0,4.4,94.8,8.0,0,1,0,1,0,34.3,0,1,0,0,1,0,0
3,23,1.0,0,4.9,71.0,9.2,0,4,2,1,1,26.8,1,0,0,0,0,1,0
4,19,5.0,0,4.9,90.9,4.9,1,3,2,1,0,66.4,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,2.6,0,2.1,77.0,7.5,1,2,2,6,1,76.1,1,0,0,0,1,0,0
996,17,2.9,1,3.4,86.0,6.8,0,1,1,6,1,65.9,1,0,0,0,1,0,0
997,20,3.0,0,3.9,61.9,6.5,2,5,2,9,1,64.4,0,1,0,1,0,0,0
998,24,5.4,1,5.2,100.0,7.6,1,0,1,1,0,69.7,0,1,0,1,0,0,0
999,19,4.3,0,4.8,89.4,7.1,2,2,1,8,0,74.9,1,0,0,1,0,0,0

In [7]:
st_habits1.isnull().sum()

age                     0
study_hrs               0
part_time_job           0
media_hrs               0
att_percent             0
sleep_hours             0
diet_quality            0
exercise_fq             0
internet_quality        0
mental_health_rating    0
extracurricular         0
exam_score              0
gender_Female           0
gender_Male             0
gender_Other            0
par_edu_Bachelor        0
par_edu_High School     0
par_edu_Master          0
par_edu_Unknown         0
dtype: int64

In [8]:
st_habits1.columns

Index(['age', 'study_hrs', 'part_time_job', 'media_hrs', 'att_percent',
       'sleep_hours', 'diet_quality', 'exercise_fq', 'internet_quality',
       'mental_health_rating', 'extracurricular', 'exam_score',
       'gender_Female', 'gender_Male', 'gender_Other', 'par_edu_Bachelor',
       'par_edu_High School', 'par_edu_Master', 'par_edu_Unknown'],
      dtype='object')